CREATE DATABASE IF NOT EXISTS stock;

USE stock;


CREATE TABLE IF NOT EXISTS market (
	id VARCHAR(10) NOT NULL,
	name VARCHAR(256) NOT NULL,
	PRIMARY KEY (id)
)
COMMENT='市場類別'
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS industry (
	market_id VARCHAR(10) NOT NULL COMMENT '市場類別的id',
	id VARCHAR(10) NOT NULL,
	name VARCHAR(256) NOT NULL,
	PRIMARY KEY (`market_id`,`id`) USING BTREE
)
COMMENT='產業類別'
 ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS company (
	id INT NOT NULL AUTO_INCREMENT,
	stock_code VARCHAR(20) NOT NULL COMMENT '股票代碼',
	company_name VARCHAR(256) NOT NULL,
	short_name VARCHAR(256) NOT NULL COMMENT '簡稱',
	market_id VARCHAR(10) NOT NULL,
	industry_id VARCHAR(10) NOT NULL,
	
	founding_date DATE  NULL COMMENT '成立日期',
	ipo_date DATE  NULL COMMENT '上市日期',
	
	source_time DATETIME NOT NULL COMMENT '資料日期',
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '更新時間',
	PRIMARY KEY (id)
)
COMMENT='公司資料'
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS second_price_2024_2330 (
	id INT NOT NULL AUTO_INCREMENT,
	source_time DATETIME NOT NULL,
	latest_trade_price DECIMAL(6,4) NOT NULL,
	trade_volume INT NOT NULL,
	accumulate_trade_volume INT NOT NULL,
	
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

	PRIMARY KEY (id)
)
COMMENT='2330在2024年的每5秒收盤價'
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS day_price_2024 (
	id INT NOT NULL AUTO_INCREMENT,
	source_time DATETIME NOT NULL,
	`open` DECIMAL(6,4) NOT NULL,
	high DECIMAL(6,4) NOT NULL,
	low DECIMAL(6,4) NOT NULL,
	
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

	PRIMARY KEY (id)
)
COMMENT='2024年的每天收盤價'
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS observe_group(
	id INT NOT NULL AUTO_INCREMENT,
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

	PRIMARY KEY (id)
)
COMMENT='觀察的條件群組'
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS observe_condition(
	id INT NOT NULL AUTO_INCREMENT,
	condi_type int NOT NULL,/*條件類型*/
	condi_name VARCHAR(255) NOT NULL,/*條件名稱*/
	remark VARCHAR(255) NOT NULL,
	observe_group_id INT NOT NULL,/*觀察的群組id*/
	
	update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

	PRIMARY KEY (id)
)
COMMENT='要觀察的條件'
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;